# Generated by Django 2.1.5 on 2019-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField()),
                ('filth', models.IntegerField()),
                ('day_light', models.IntegerField()),
                ('milk', models.IntegerField()),
                ('milk_val', models.IntegerField()),
                ('eggs', models.IntegerField()),
                ('eggs_val', models.IntegerField()),
                ('bacon', models.IntegerField()),
                ('bacon_val', models.IntegerField()),
                ('money', models.IntegerField()),
                ('wallet', models.IntegerField()),
                ('cow_price', models.IntegerField()),
                ('cow_count', models.IntegerField()),
                ('pig_price', models.IntegerField()),
                ('pig_count', models.IntegerField()),
                ('coop_price', models.IntegerField()),
                ('coop_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
